# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 2AM daily
    - cron: '0 2 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fd296539c49c96748d407d0
